<?php
$helper = $this->helper("Ves\Blog\Helper\Data");
$title = $helper->getConfig('sidebar/searchform_title');
?>
<div class="ves-block block blog-searchform">
	<?php if($title) : ?>
	<div class="block-title">
		<strong><?= __('Search Form'); ?></strong>
	</div>
	<?php endif; ?>
	<div class="block-content">
		<form method="get" class="search-form" action="<?= $block->escapeUrl($helper->getSearchFormUrl()); ?>" data-mage-init='{"validation":{}}'>
			<input type="text" class="search-field required-entry" placeholder="<?= $block->escapeHtmlAttr(__('Search posts here…')); ?>" value="<?= $block->escapeHtmlAttr($helper->getSearchKey()) ?>" name="s" title="<?= $block->escapeHtmlAttr(__('Search for:')); ?>">
			<button type="submit" class="search-submit"><i class="fa fa-search"></i></button>
		</form>
	</div>
</div>
