<?php
$helper = $this->helper('\Ves\Blog\Helper\Data');
$category = $helper->getCoreRegistry()->registry('current_post_category');
$image = $category->getImage();
$description = $category->getDescription();
?>
<?php if($image!='' && $category->getIsActive()){ ?>
<?php $imgUrl = $helper->getMediaUrl($image); ?>
<img src="<?= $imgUrl ?>" alt="<?= $category->getName() ?>"/>
<?php } ?>
<?php if($description && $category->getIsActive()){ ?>
<div class="blogcat-description"><?= $description ?></div>
<?php } ?>
