<?php
$collection  = $this->getCollection();
$helper      = $this->helper("Ves\Blog\Helper\Data");
$imageHelper = $this->helper("Ves\Blog\Helper\Image");
$blockId = 'blog-list'. time();
?>
<?php if($collection->count()){ ?>
<?php $total = count($collection->getItems()); ?>
<div class="ves-blog authors-list">
	<div class="blog-list <?= $blockId; ?>  blog-authors">
		<!-- List author: name with link, avatar, number posts, social, website -->
		<ul class="authors-listing">
		<?php $i = 1; ?>
		<?php foreach($collection as $author) { ?>
		<?php $class = (($i/2)==0)?'list-obb':''; $i++; ?>
		<li <?= $class?('class="'.$class.'"'):''; ?>>
			<div id="author-box">
				<div class="block-title"><h2><a href="<?= $helper->getAuthorUrl($author); ?>" title="<?= $author->getNickName() ?>"><?= $author->getNickName(); ?></a></h2></div>
				<div class="block-content">
					<?php if($avatar = $author->getAvatar()){ ?>
					<div class="author-avatar">
					<a href="<?= $helper->getAuthorUrl($author); ?>" title="<?= $author->getNickName() ?>">
						<img src="<?= $imageHelper->resizeImage($avatar, 125, 125) ?>" alt="" height="125" width="125">
					</a>
					</div>
					<?php } ?>

					<?php if($number_posts = $author->getTotalPosts()){ ?>
					<div class="author-posts"><a href="<?= $helper->getAuthorUrl($author); ?>" title="<?= __("View all posts") ?>"><?= __("%1 posts", $number_posts); ?></a></div>
					<?php } ?>

					<?php if($bio = $author->getDescription()){ ?>
					<div class="author-description"><?= $helper->filter($bio) ?></div>
					<?php } ?>

					<?php $authorSocials = @unserialize($author->getSocialNetworks()); ?>
					<?php if(!empty($authorSocials)){ ?>
					<div class="author-social flat-social">
						<?php foreach ($authorSocials as $k => $v) { ?>
							<?php if(trim($v)!=''){ ?>
							<a class="social-<?= $k ?>" href="<?= $v; ?>"><i class="fa fa-<?= $k ?>"></i></a>
							<?php } ?>
						<?php } ?>
					</div>
					<?php } ?>
				</div>
			</div>
		</li>
		<?php } ?>
		</ul>
	</div>
	<div class="blog-toolbar">
		<?= $block->getChildHtml('toolbar'); ?>
	</div>
</div>
<?php } ?>
